### ISSUE TITLE
Add support for Tags

### ISSUE THREAD

**Issue by jimeh** [krystal/terraform-provider-katapult#100]
The ability to manage [Tags](https://apidocs.k.io/katapult/groups/tags/) in Terraform.

## Tasks

- [ ] Add `katapult_tag` resource, with attributes:
  - `id` (computed)
  - `name`
  - `color`
- [ ] Add `katapult_tag` data source, with attributes:
  - `id`
  - `name`
  - `color`
- [ ] Add `katapult_tags` data source to list all tags, with a `tags` attribute that is a list of tags using the same schema as the `katapult_tag` data source.

**Comment by jpswade** [comment]
We need the API first.

**Comment by ikadix** [comment]
AFAICT only thing missing from the API for this would be returning the tag color in the [list tags response](https://apidocs.k.io/katapult/routes/organizations/:organization/tags/get/). 

We could make an individual request for each tag in the list to get the color but it feels like fixing this in the API would be preferable. 

We can also go ahead and release this without color in the `katapult_tags` data source in the meantime I imagine.
