### ISSUE TITLE
Milestone 0: Quick Wins — Overview

### ISSUE THREAD

**Issue by jimehk** [krystal/terraform-provider-katapult#147]
A handful of smaller highly requested features we want to get out sooner rather than later, with a focus on managing virtual networks attached to virtual machines.

This issue serves as a high-level outline/overview of the milestone, with individual issues to be spun out as sub-issues here, and added to the [Quick Wins](https://github.com/krystal/terraform-provider-katapult/milestone/2) milestone.

## Resources

- [x] Virtual Machines (#153)
    - [x] `virtual_network_ids` attribute to manage network interfaces connected to specified virtual networks.
    - [x] `network_interfaces` read-only property.
- [x] Virtual Networks (#151)

## Data Sources

- [x] Network (#79)
    - [x] Get list
        - Each network should include a `default` boolean attribute indicating if it is the default network for the current data center.
    - [x] Get by `id`
    - [x] Get by `permalink`
    - [x] Get by `default`
        - Returns the network marked as default for the current data center.
- [x] Virtual Machines (#153)
    - [x] `network_interfaces` read-only property.
    - [x] `virtual_network_ids` read-only property.
- [x] Virtual Networks (#152)
    - [x] Get list
    - [x] Get by `id`

**Comment by jimehk** [comment]
This was completed with the release v0.0.15: https://github.com/krystal/terraform-provider-katapult/releases/tag/v0.0.15
