### ISSUE TITLE
Prepare for initial (alpha) release on Terraform Registry

### ISSUE THREAD

**Issue by jimeh** [krystal/terraform-provider-katapult#15]
In order to release a provider on the Terraform Registry, some preparation is needed, full details are available [here](https://www.terraform.io/docs/registry/providers/publishing.html).

Below is a summary of the steps outstanding:

- [x] Add a license. (#20)
- [x] [Provider Documentation](https://www.terraform.io/docs/registry/providers/docs.html), can be generated with the help of [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs). Fleshing out some example files will probably be needed. (#17)
- [ ] Setup automatic release generation with goreleaser and GitHub Actions. This will also include generating a GPG signing key, which will be used to sign all released binaries. This is required as the `terraform` CLI tool will validate all binaries against the public key published on the Terraform Registry. (#18)
- [ ] Add information to the README. (#16)
- [ ] Publish the provider on the Terraform Registry. (#19)

I think the very first version should probably be a pre-release version, e.g. `v0.0.1-alpha.0`. As detailed [here](https://www.terraform.io/docs/registry/providers/publishing.html#creating-a-github-release) pre-releases are supported, but need to explicitly specified as the desired provider version. If no version is specified, Terraform will only pick the latest stable version available for a provider.

**Comment by jimeh** [comment]
I'm closing this issue in favor of tracking progress in the [Public Release (alpha)](https://github.com/krystal/terraform-provider-katapult/milestone/1) milestone instead.
