### ISSUE TITLE
Migrate from Terraform Plugin SDKv2 to new Provider Framework

### ISSUE THREAD

**Issue by jimeh** [krystal/terraform-provider-katapult#97]
Terraform's Plugin SDK was recently superseded by the Plugin Framework:

- https://developer.hashicorp.com/terraform/plugin/framework
- https://github.com/hashicorp/terraform-plugin-framework

Providers can be slowly migrated piece by piece over to the new framework, by hosting both protocol v5 (SDKv2) and v6 (Framework) providers within the same one provider binary:

- https://developer.hashicorp.com/terraform/plugin/mux/translating-protocol-version-5-to-6

## Tasks

- [ ] Setup plugin Framework for new resources, while still serving existing ones using the [`tf5to6server`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-mux/tf5to6server) package, as documented [here](https://developer.hashicorp.com/terraform/plugin/mux/translating-protocol-version-5-to-6).
- [ ] Migrate Resources to Framework:
  - [ ] `katapult_ip`
  - [ ] `katapult_security_group`
  - [ ] `katapult_security_group_rule`
  - [ ] `katapult_virtual_machine`
  - [ ] `katapult_virtual_machine_group`
- [ ] Migrate Data Sources to Framework:
  - [ ] `katapult_data_center`
  - [ ] `katapult_disk_template`
  - [ ] `katapult_disk_templates`
  - [ ] `katapult_ip`
  - [ ] `katapult_network_speed_profile`
  - [ ] `katapult_network_speed_profiles`
  - [ ] `katapult_security_group`
  - [ ] `katapult_security_group_rule`
  - [ ] `katapult_security_group_rules`
  - [ ] `katapult_security_groups`
  - [ ] `katapult_virtual_machine`
  - [ ] `katapult_virtual_machine_group`
  - [ ] `katapult_virtual_machine_groups`
  - [ ] `katapult_virtual_machine_package`
  - [ ] `katapult_virtual_machine_packages`
- [ ] Use Framework for any new Resources and Data Sources.
